name = "auth-template"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2025-02-10"
compatibility_flags = [ "nodejs_compat_v2" ]

[vars]
PUBLIC_BETTER_AUTH_URL = "http://localhost:5173"
