name = "auth-template"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-02-10"
compatibility_flags = ["nodejs_compat_v2"]

[site]
bucket = ".svelte-kit/output"

[vars]
PUBLIC_BETTER_AUTH_URL = "https://auth-template.workers.dev"
NODE_VERSION = "22.14.0"

[build]
command = "npm run build"